#!/usr/bin/env bash

ai() {
	local assignment name types warnings=()

	while IFS= read -r; do
		assignment=${REPLY#alias }
		name=${assignment%=*}

		mapfile -t types < <(type -at "$name")

		for type in "${types[@]}"; do
			case "$type" in
			builtin)
				warnings+=($'The alias \e[33m'$name$'\e[0m overrides a builtin of the same name.')
				;;
			file)
				warnings+=($'The alias \e[33m'$name$'\e[0m overrides a shell command of the same name.')
				;;
			esac
		done

	done < <(alias)

	if ((${#warnings[@]} > 0)); then
		for warning in "${warnings[@]}"; do
			printf '%s\n' "$warning"
		done

		return 1
	fi

        printf '\e[32mNo shell command or builtin is overridden.\e[0m\n'
}
